<?xml version='1.0'?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="bodyLen" value="0.2"/>
<xacro:property name="bodyWidth" value="0.4"/>
<xacro:property name="bodyHeight" value="0.05"/>
<xacro:property name="bodyRadius" value="0.2"/>

<xacro:property name="M_PI" value="3.1415926535897931" />

<!-- define the drive-wheel dimensions-->
<xacro:property name="tireDiam" value="0.125" />
<xacro:property name="tireRad" value="${tireDiam/2.0}" />    
<xacro:property name="tireWidth" value="0.05" />
<xacro:property name="track" value="${bodyWidth + tireWidth}" />

<!-- placement of main body relative to base link frame -->
<xacro:property name="bodyOX" value="0" />  
<xacro:property name="bodyOY" value="0" />   
<xacro:property name="bodyOZ" value="${tireRad}" />   

<!-- Caster wheel -->
<xacro:property name="casterRad" value="${(tireDiam - bodyHeight)/2.0 + 0.0125}"/>

<!-- Camera -->
<xacro:property name="camera_link" value="0.025" /> <!-- Size of square 'camera' box -->


</robot> 
