<?xml version="1.0"?>
<robot 
     xmlns:xacro="http://www.ros.org/wiki/xacro" name="static_links">
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${bodyLen} ${bodyWidth} ${bodyHeight}"/>
            </geometry>
            <origin xyz="${bodyOX} ${bodyOY} ${bodyOZ}" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${bodyLen} ${bodyWidth} ${bodyHeight}"/>
            </geometry>
            <origin xyz="${bodyOX} ${bodyOY} ${bodyOZ}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <!--assign almost all the mass to the main body box; set m= 100kg; treat I as approx m*r^2 -->
            <mass value="100" />
            <inertia ixx="10" ixy="0" ixz="0"
              iyy="10" iyz="0"
              izz="10" />
        </inertial>
    <collision name='caster_collision'>
      <origin xyz="${bodyRadius} 0 ${casterRad}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${casterRad}"/>
      </geometry>
    </collision>

    <visual name='caster_visual'>
      <origin xyz="${bodyRadius} 0 ${casterRad}" rpy=" 0 0 0"/>
      <geometry>
          <sphere radius="${casterRad}"/>
      </geometry>
    </visual>
    </link>
    <link name="base_link_1">
        <visual>
            <geometry>
                <cylinder radius="${bodyRadius}" length="${bodyHeight}"/>
            </geometry>
            <origin xyz="${bodyLen/2.0} 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${bodyRadius}" length="${bodyHeight}"/>
            </geometry>
            <origin xyz="${bodyLen/2.0} 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <!--assign almost all the mass to the main body box; set m= 100kg; treat I as approx m*r^2 -->
            <mass value="100" />
            <inertia ixx="10" ixy="0" ixz="0"
              iyy="10" iyz="0"
              izz="10" />
        </inertial>
    </link>
    <joint name="base_to_base_1" type="fixed">
        <parent link="base_link"/>
        <child link="base_link_1"/>
        <origin xyz="${bodyOX} ${bodyOY} ${bodyOZ}" rpy="0 0 0"/>
    </joint>
</robot>
