TrajectoryPlannerROS:

#  heading_scoring: true

# Differential-drive robot configuration
  holonomic_robot: false
  meter_scoring:        true
  yaw_goal_tolerance:   0.10
  xy_goal_tolerance:    0.10


