map_type: costmap

obstacle_range: 5.0
raytrace_range: 6.0

transform_tolerance: 0.1

inflation_radius: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /my_robot/laser/scan, marking: true, clearing: true}
