global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 40.0
   height: 40.0
   resolution: 0.1
   static_map: true
   rolling_window: false
